SELECT TOP (1000) [ProjectKey]
      ,[CompanyKey]
      ,[ProjectID]
      ,[Description]
      ,[StartDate]
      ,[EndDate]
      ,[ActiveProject]
      ,[CurrencyCode]
      ,[Plant]
      ,[PrimaryJob]
      ,[PrimaryMtl]
      ,[Revision]
      ,[InsertDate]
      ,[InsertedBy]
      ,[LastUpdatedDate]
      ,[LastUpdatedBy]
      ,[HashKey]
      ,[RecActiveInd]
      ,[RecEffStartDate]
      ,[RecEffEndDate]
      ,[CurrencyKey]
  FROM [dbo].[DimProject]
    WHERE ProjectID='2170022'