SELECT TOP (1000) [Company]
      ,[FiscalCalendarID]
      ,[FiscalYear]
      ,[FiscalYearSuffix]
      ,[FiscalPeriod]
      ,[StartDate]
      ,[EndDate]
      ,[FAClosedPeriod]
      ,[AdditionalDeductions]
      ,[LossesCredit]
      ,[InvestmentCredit]
      ,[InventoriesCredit]
      ,[UpdateRate]
      ,[DepHoliday]
      ,[SysRevID]
      ,[SysRowID]
      ,[JPYear]
  FROM [ERPDB].[Erp].[FiscalPer]
  Where Company = 'Solar'
  Order by FiscalYear DESC