SELECT TOP (1000) [Company]
      ,[FiscalYear]
      ,[JournalNum]
      ,[JournalLine]
      ,[Description]
      ,[JEDate]
      ,[FiscalPeriod]
      ,[GroupID]
      ,[PostedBy]
      ,[PostedDate]
      ,[Posted]
      ,[SourceModule]
      ,[VendorNum]
      ,[APInvoiceNum]
      ,[JournalCode]
      ,[ARInvoiceNum]
      ,[BankAcctID]
      ,[CheckNum]
      ,[Reverse]
      ,[BankSlip]
      ,[RefType]
      ,[RefCode]
    --   ,[GlbJournalNum]
    --   ,[GlbJournalLine]
    --   ,[GlbJournalCode]
    --   ,[GlbVendorNum]
    --   ,[GlbAPInvoiceNum]
    --   ,[MultiCompany]
    --   ,[Linked]
    --   ,[CommentText]
    --   ,[GlbCompanyID]
    --   ,[GlbFiscalYear]
    --   ,[GlbFiscalPeriod]
    --   ,[GlbGroupID]
      ,[COACode]
      ,[GLAccount]
      ,[SegValue1]
      ,[SegValue2]
      ,[SegValue3]
      ,[BookID]
      ,[CreateDate]
      ,[CurrencyCode]
      ,[LegalNumber]
      ,[PerBalFlag]
      ,[TBFlag]
      ,[DailyBalFlag]
      ,[FiscalYearSuffix]
      ,[FiscalCalendarID]
    --   ,[GlbFiscalYearSuffix]
    --   ,[GlbFiscalCalendarID]
    --   ,[IntermediateProc]
    --   ,[GenID]
    --   ,[SrcCompany]
    --   ,[SrcBook]
    --   ,[SrcGLAccount]
    --   ,[SrcJrnlCode]
    --   ,[SrcJournalNum]
    --   ,[SrcJournalLine]
    --   ,[SrcType]
      ,[ABTUID]
      ,[DebitAmount]
      ,[CreditAmount]
      ,[BookDebitAmount]
      ,[BookCreditAmount]
      ,[ParentRUID]
      ,[HasReverseLine]
      ,[BalanceAcct]
      ,[TrialAcct]
      ,[CorrAccUID]
      ,[AllocationStamp]
      ,[BatchID]
      ,[AllocID]
      ,[RunNbr]
      ,[AllocRunNbr]
      ,[AllocTgtNbr]
      ,[AllocTgtSeq]
      ,[ExtCOACode]
      ,[MatchCode]
      ,[MatchDate]
      ,[Reconciled]
    --   ,[Statistical]
    --   ,[StatUOMCode]
      ,[SysRevID]
      ,[SysRowID]
    FROM [ERPDB].[Erp].[GLJrnDtl] as gld
  Where Company = 'Solar'
    And gld.FiscalYear = 2022
    And (gld.Segvalue1 >= 4000 and gld.Segvalue1 <= 9999)
    -- And PostedDate <= '2022-08-10'
    -- And JEDate <= '2022-07-31'
  Order by PostedDate DESC