SELECT TOP (1000) [ProjectID]
      ,[Company]
      ,[Date]
      ,[DivisionID]
      ,[ProjMgrEmpID]
      ,[DailyBaseEstimate]
      ,[DailyBaseEstimateChg]
      ,[DailySellPrice]
      ,[DailySellPriceChg]
      ,[DailyCost]
      ,[DailyCostChg]
      ,[DailyOpenJobDemands]
      ,[DailyOpenJobDemandsChg]
      ,[DailyCurrentEstimate]
      ,[DailyCurrentEstimateChg]
      ,[DailyPctComplete]
      ,[DailyPctCompleteChg]
      ,[DailyRevenue]
      ,[DailyRevenueChg]
      ,[DailyGrossMargin]
      ,[DailyGrossMarginChg]
      ,[DailyGrossMarginPct]
      ,[DailyGrossMarginPctChg]
      ,[PrevDate]
  FROM [dw].[FactGrossMargin]
Where Company = 'Solar'
        and ProjectID = 2230115
  order by Date Desc