  
  Select top (10)
    jm.SysRowID,     
     jm.Company,  
     jm.Latest_ChangeDate AS Date,  
     jm.Latest_ChangeDateTime AS ChangeDateTime,     
     jm.ProjectID,     
     jm.OrderNum,     
     jm.OrderNumLine,     
     jm.PartNum,     
     jm.JobNum,     
     jm.JobComplete,     
     jm.IssuedComplete,     
     jm.ReqDate,     
     jm.AssemblySeq,     
     jm.MtlSeq,     
     TotalCost,     
     EstUnitCost,     
     jm.IssuedQty,     
     RequiredQty,     
     ((RequiredQty) * EstUnitCost) AS OpenJobDemands,     
     jm.Description,     
     jm.QtyPer,     
     jm.IUM,     
     jm.LeadTime,     
     jm.RelatedOperation,     
     jm.MtlBurRate,     
     jm.EstMtlBurUnitCost,     
     jm.MtlBurCost,     
     jm.WarehouseCode,     
     jm.MfgComment,     
     jm.VendorNum,     
     jm.PurPoint,     
     jm.BuyIt,     
     jm.PurComment,     
     jm.RevisionNum,     
     jm.Plant,     
     jm.MaterialMtlCost,     
     jm.MaterialLabCost,     
     jm.MaterialSubCost,     
     jm.MaterialBurCost,     
     jm.ProdCode,     
     jm.UnitPrice,     
     jm.PricePerCode,     
     jm.ShippedQty,     
     jm.DocUnitPrice,     
     jm.MiscCharge,     
     jm.MiscCode,     
     jm.Weight,     
     jm.WeightUOM,     
     jm.EstMtlUnitCost,     
     jm.EstLbrUnitCost,     
     jm.EstBurUnitCost,     
     jm.EstSubUnitCost    
    FROM  [ERPDB].[etl].[vwJobMtlChange] jm
    WHERE ISNUMERIC(jm.ProjectID)=1  and  jm.Latest_ChangeDate IS NOT NULL AND jm.ProjectID IS NOT NULL