SELECT TOP (1000) [Company]
      ,[OrderNum]
      ,[OrderLine]
      ,[OrderRelNum]
      ,[ReqDate]
      ,[OurReqQty]
      ,[OpenRelease]
      ,[FirmRelease]
      ,[OurJobQty]
      ,[OurJobShippedQty]
      ,[VoidRelease]
      ,[OurStockQty]
      ,[WarehouseCode]
      ,[OurStockShippedQty]
      ,[PartNum]
      ,[NeedByDate]
      ,[ChangedBy]
      ,[ChangeDate]
      ,[ChangeTime]
    ,[PrevNeedByDate]
      ,[PrevReqDate]
        ,[MFCustNum]
      FROM [ERPDB].[Erp].[OrderRel]
  Where Ordernum = '2170100'
  Order by company, orderline