SELECT TOP (1000) [VoidLine]
      ,[OpenLine]
      ,[Company]
      ,[OrderNum]
      ,[OrderLine]
      ,[LineType]
      ,[PartNum]
      ,[LineDesc]
      ,[UnitPrice]
      ,[OrderQty]
      ,[RequestDate]
      ,[ProdCode]
      ,[NeedByDate]
      ,[ProjectID]
      ,[ChangedBy]
      ,[ChangeDate]
  FROM [ERPDB].[Erp].[OrderDtl]
  Where ordernum = '2170100'
  Order by company, orderline
